package com.github.NikBenson.RoleplayBot.configurations;

public class ConfigurationPaths {
	private ConfigurationPaths() {}

	public static final String REPEATED_MESSAGES_DIRECTORY = "RepeatedMessages/";

	public static final String BOT_INFO_FILE = "botinfo.json";
	public static final String GAME_CYCLE_FILE = "gameconfig.json";
	public static final String WELCOME_MESSAGE_FILE = "welcomemessage.json";
	public static final String MANUALS_FILE = "manuals.json";
	public static final String CHARACTER_GENERATION_FILE = "charactergeneration.json";
	public static final String TEAMS_FILE = "teams.json";

	public class Autogenerated {
		private Autogenerated() {}

		public static  final String ROOT = ".autogenerated";
		public static final String PLAYERS_FILE = "players.json";
		public static final String STORAGE_FILE = "storage.json";
	}
}
